version: "3.8"

services:
  fastapi-app:
    build: .
    container_name: fastapi_container
    ports:
      - "8003:8000"  # HostPort:ContainerPort
    environment:
      - PYTHONDONTWRITEBYTECODE=1
